# Codecov Configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "50...100"

  status:
    project:
      default:
        target: auto
        threshold: 10%  # 커버리지 10% 이상 감소하면 실패
        informational: true  # 정보 제공용 (빌드 실패 안 함)

    patch:
      default:
        target: 40%  # 새 코드 40% 이상이면 OK
        informational: true  # 정보 제공용 (빌드 실패 안 함)

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

flags:
  backend:
    paths:
      - lupin/src/main/java/
    carryforward: true

  frontend:
    paths:
      - src/
    carryforward: true

ignore:
  - "**/*Test.java"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "**/test/**"
  - "**/tests/**"
  - "**/__tests__/**"
  - "**/e2e/**"
  - "**/*.d.ts"
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/build/**"
